# Generated by Django 3.2.6 on 2022-02-12 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_passenger'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passenger',
        ),
    ]
